- docs/pages/2.setup.md
- docs/pages/4.advanced.md
- package.json
- src/composables/useInitIndex.ts
- src/crawler/index.ts
- src/hooks/crawler.ts
- src/module.ts
- src/types/index.ts
- yarn.lock
Refers to: https://github.com/nuxt-modules/algolia/issues/8
> feat: metadata crawler

- package.json
- yarn.lock
Remove "metascraper" dependency from previous merged PR #9
> chore: remove metascraper

- docs/pages/2.setup.md
- package.json
- playground/app.vue
- playground/nuxt.config.ts
- src/module.ts
- src/runtime/plugin.ts
- yarn.lock
Refers to: https://github.com/nuxt-modules/algolia/issues/1
> feat: vue-instantsearch

- CHANGELOG.md
- package.json
> chore(release): 0.7.0

- docs/pages/4.advanced.md
- playground/app.vue
- playground/types.d.ts
- src/module.ts
- src/runtime/composables/useInitIndex.ts
- src/runtime/composables/useSearch.ts
- src/runtime/composables/useSearchForFacetValues.ts
- src/types.ts
- tsconfig.json
from: https://github.com/nuxt-community/algolia-module/discussions/24
> feat: search results type from index name

- README.md
- docs/pages/1.index.md
- docs/pages/2.setup.md
- docs/pages/4.advanced.md
- docs/pages/5.examples.md
- package.json
- src/module.ts
> chore: updated docs

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/question.md
I have updated the issue templates, **these changes do not affect the module itself.**
> chore(fix) Issue template fixed

- src/module.ts
No compatibility options were set in the module meta settings
> fix: provided compatibility options

- docs/pages/4.advanced.md
> fix: #50 fix docs about vue-instantsearch

- playground/pages/index.vue
- src/runtime/plugin.ts
> fix: #61 vue-instantsearch plugin

- docs/content/1.getting-started/3.usage.md
- src/runtime/composables/useAlgolia.ts
- src/runtime/composables/useInitIndex.ts
- src/runtime/composables/useSearch.ts
- src/runtime/composables/useSearchForFacetValues.ts
Reverts nuxt-community/algolia-module#74
> Revert "feat: #69 remove deprecated composables"

- docs/content/1.getting-started/1.quick-start.md
- docs/content/2.advanced/3.indexer.md
> docs: #72 quick-start docs

- package.json
- src/module.ts
> Chore/release 1.1.1

- package.json
- yarn.lock
> chore: bump nuxt and version

- CHANGELOG.md
- README.md
- docs/content/1.index.md
- docs/content/2.advanced/3.docsearch.md
- docs/content/_theme.yml
- docs/nuxt.config.js
- package.json
> chore: #94 replace community with modules

- package.json
- src/module.ts
> chore: 1.1.3

- package.json
- src/module.ts
> chore: 1.1.4

- src/runtime/components/AlgoliaDocSearch.vue
> fix: don't import docsearch css for server build

- src/runtime/plugin.ts
remove console.log
Removed console.log
Just removed a console.log
> Remove console.log

- README.md
- docs/content/1.getting-started/1.quick-start.md
- docs/content/1.getting-started/3.usage.md
- docs/content/1.index.md
- playground/pages/index.vue
- src/runtime/composables/useAlgoliaSearch.ts
> feat: add SSR support

- package.json
- src/module.ts
- yarn.lock
> fix: node polyfills

- package.json
- src/module.ts
> fix: ssr support

- docs/content/1.getting-started/1.quick-start.md
- docs/content/1.getting-started/2.configuration.md
- docs/content/1.getting-started/3.usage.md
- playground/nuxt.config.ts
- src/module.ts
> feat: support env vars

- README.md
> feat: update Stackblitz link

- README.md
- docs/content/1.getting-started/1.quick-start.md
> docs: correct template code

- docs/content/2.advanced/5.crawler.md
- playground/nuxt.config.ts
- playground/pages/index.vue
- playground/pages/other-page.vue
- src/hooks/crawler.ts
- src/module.ts
> feat: add crawler support for Nuxt 3

- package.json
- playground/pages/index.vue
- src/runtime/components/AlgoliaDocSearch.vue
- src/runtime/composables/useAlgoliaSearch.ts
- src/runtime/composables/useAsyncAlgoliaSearch.ts
- src/runtime/plugin.ts
- yarn.lock
> chore: update to nuxt 3.4

- docs/content/1.getting-started/3.usage.md
- src/runtime/composables/useAsyncAlgoliaSearch.ts
Multiple useAsyncAlgoliaSearch calls would overwrite each other if done on same index. Added optional key parameter
> Added key to useAsyncAlgoliaSearch

- docs/content/1.getting-started/3.usage.md
- src/runtime/composables/useAlgoliaRecommend.ts
Multiple useAlgoliaRecommend calls would overwrite the 'recommend-result' useState. Added an optional key param to make it unique composable
> Added optional key to useAlgoliaRecommend

- docs/content/2.advanced/3.docsearch.md
- playground/nuxt.config.ts
- src/runtime/components/AlgoliaDocSearch.vue
- src/types.ts
> feat!(docsearch): remove default `facetFilters`
